spring:
  application:
    name: insightdocs
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/insightdocs
    username: ritesh
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: my-super-secret-key-that-is-at-least-32-characters-long-for-security
  expiration: 86400000